name: jombe_digital_mobile
description: "Aplikasi Mobile Pelayanan Desa Jombe untuk Warga"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  dio: ^5.4.1
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  file_picker: ^8.0.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
